"""Second migration

Revision ID: 5af90668be78
Revises: 
Create Date: 2023-08-29 09:17:53.682358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af90668be78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_chats_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_chats_sender_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gomokutables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_black_id', sa.Integer(), nullable=True),
    sa.Column('player_white_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_black_id'], ['users.id'], name=op.f('fk_gomokutables_player_black_id_users')),
    sa.ForeignKeyConstraint(['player_white_id'], ['users.id'], name=op.f('fk_gomokutables_player_white_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tictactoetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_x_id', sa.Integer(), nullable=True),
    sa.Column('player_o_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_o_id'], ['users.id'], name=op.f('fk_tictactoetables_player_o_id_users')),
    sa.ForeignKeyConstraint(['player_x_id'], ['users.id'], name=op.f('fk_tictactoetables_player_x_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gomokus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_black_id', sa.Integer(), nullable=False),
    sa.Column('player_white_id', sa.Integer(), nullable=False),
    sa.Column('current_player_id', sa.Integer(), nullable=False),
    sa.Column('game_status', sa.String(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_player_id'], ['users.id'], name=op.f('fk_gomokus_current_player_id_users')),
    sa.ForeignKeyConstraint(['player_black_id'], ['users.id'], name=op.f('fk_gomokus_player_black_id_users')),
    sa.ForeignKeyConstraint(['player_white_id'], ['users.id'], name=op.f('fk_gomokus_player_white_id_users')),
    sa.ForeignKeyConstraint(['table_id'], ['gomokutables.id'], name=op.f('fk_gomokus_table_id_gomokutables')),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], name=op.f('fk_gomokus_winner_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tictactoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_x_id', sa.Integer(), nullable=False),
    sa.Column('player_o_id', sa.Integer(), nullable=False),
    sa.Column('current_player_id', sa.Integer(), nullable=False),
    sa.Column('game_status', sa.String(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_player_id'], ['users.id'], name=op.f('fk_tictactoes_current_player_id_users')),
    sa.ForeignKeyConstraint(['player_o_id'], ['users.id'], name=op.f('fk_tictactoes_player_o_id_users')),
    sa.ForeignKeyConstraint(['player_x_id'], ['users.id'], name=op.f('fk_tictactoes_player_x_id_users')),
    sa.ForeignKeyConstraint(['table_id'], ['tictactoetables.id'], name=op.f('fk_tictactoes_table_id_tictactoetables')),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], name=op.f('fk_tictactoes_winner_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gomokusteps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('step_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['gomokus.id'], name=op.f('fk_gomokusteps_game_id_gomokus')),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], name=op.f('fk_gomokusteps_player_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tictactoesteps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('step_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['tictactoes.id'], name=op.f('fk_tictactoesteps_game_id_tictactoes')),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], name=op.f('fk_tictactoesteps_player_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tictactoesteps')
    op.drop_table('gomokusteps')
    op.drop_table('tictactoes')
    op.drop_table('gomokus')
    op.drop_table('tictactoetables')
    op.drop_table('gomokutables')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
