"""Second migration

Revision ID: a02c23edfd03
Revises: d3b8f0068b8e
Create Date: 2023-08-29 03:30:45.317696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02c23edfd03'
down_revision = 'd3b8f0068b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gomokutables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_black_id', sa.Integer(), nullable=True),
    sa.Column('player_white_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_black_id'], ['users.id'], name=op.f('fk_gomokutables_player_black_id_users')),
    sa.ForeignKeyConstraint(['player_white_id'], ['users.id'], name=op.f('fk_gomokutables_player_white_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gomokus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_black_id', sa.Integer(), nullable=False),
    sa.Column('player_white_id', sa.Integer(), nullable=False),
    sa.Column('current_player_id', sa.Integer(), nullable=False),
    sa.Column('game_status', sa.String(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_player_id'], ['users.id'], name=op.f('fk_gomokus_current_player_id_users')),
    sa.ForeignKeyConstraint(['player_black_id'], ['users.id'], name=op.f('fk_gomokus_player_black_id_users')),
    sa.ForeignKeyConstraint(['player_white_id'], ['users.id'], name=op.f('fk_gomokus_player_white_id_users')),
    sa.ForeignKeyConstraint(['table_id'], ['gomokutables.id'], name=op.f('fk_gomokus_table_id_gomokutables')),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], name=op.f('fk_gomokus_winner_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gomokusteps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('step_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['gomokus.id'], name=op.f('fk_gomokusteps_game_id_gomokus')),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], name=op.f('fk_gomokusteps_player_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gomokusteps')
    op.drop_table('gomokus')
    op.drop_table('gomokutables')
    # ### end Alembic commands ###
